### ISSUE TITLE
add getBlockTimestamp and getBlockHeight

### ISSUE THREAD

**Issue by eyalorbs** [orbs-network/orbs-contract-sdk#61]
In many cases it is necessary to know the block timestamp and height and it would be very helpful to add those functions

**Comment by EsterEdelstein** [comment]
Suggestion to add 2 commands:
- `get-last-block` - returners the height of the  last block  that was committed to the virtual chain . type- (uint).

- get-block-timestamp- returns the time stamp of the last block that was committed to the virtual chain . (uint):  block timestamp as seconds since unix epoch .

This 2 commands should  work with the option of  -env and with  orbs-gamma-config.json file

**Comment by talkol** [comment]
I'm pretty sure he didn't mean for gamma-cli, but for the contract SDK itself - meaning add SDK methods to allow to get these values from within running contracts

Closed in https://github.com/orbs-network/orbs-contract-sdk/commit/45ff00640dd754d3ce141d7f6fd6d5c47bbaa11d
