### ISSUE TITLE
Context: context not found error

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-contract-sdk#94]
How to reproduce:

1. install golang 1.12.6
1. check out `feature/update-orbs-contract-sdk` branch of https://github.com/orbs-network/orbs-network-go/pull/1197
1. `go run ./bootstrap/gamma/main | grep error`
1. check out `master` branch of https://github.com/orbs-network/contract-external-libraries-go
1. run go test ./examples/structs/test

Everything used to work fine last week and now it does not, I have no idea how could that be. Checked with @noambergIL  and same happens on his machine.

@electricmonk @talkol please advise.

**Comment by electricmonk** [comment]
The root cause for your issue is a linking error; `contract-external-libraries-go` imports a vendored version of `orbs-contract-sdk`. The `Context` objects reside in a package-global map here: https://github.com/orbs-network/orbs-contract-sdk/blob/master/go/context/context.go#L23

When `orbs-network-go` imports `orbs-contract-sdk`, it creates a different instance of the package, so that the global map isn't the same global map you use in your package. The solution would be to remove the vendoring of `orbs-contract-sdk` from `contract-external-libraries-go`.
